Url used to get data:

https://www.kaggle.com/datasets/shivam2503/diamonds/data

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [54]:
data = "diamonds.csv"

In [55]:
diamonds_raw = pd.read_csv(data)

diamonds_raw.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [56]:
def rename_columns(old):
    new_names = {'x':'lengh','y':'widht','z':'depth', 'carat': 'weight'}
    new = old.rename(columns=new_names)

    return new

In [61]:
diam_new = rename_columns(diamonds_raw).drop(columns='Unnamed: 0')
diam_new.head()

   weight      cut color clarity  depth  table  price  lengh  widht  depth
0    0.23    Ideal     E     SI2   61.5   55.0    326   3.95   3.98   2.43
1    0.21  Premium     E     SI1   59.8   61.0    326   3.89   3.84   2.31
2    0.23     Good     E     VS1   56.9   65.0    327   4.05   4.07   2.31
3    0.29  Premium     I     VS2   62.4   58.0    334   4.20   4.23   2.63
4    0.31     Good     J     SI2   63.3   58.0    335   4.34   4.35   2.75

In [79]:
# diam_new.value_counts
print(diam_new['cut'].drop_duplicates().count())
print(diam_new['cut'].drop_duplicates())
print('')
print(diam_new['color'].drop_duplicates().count())
print(diam_new['color'].drop_duplicates())
print('')
print(diam_new['clarity'].drop_duplicates().count())
print(diam_new['clarity'].drop_duplicates())

5
0        Ideal
1      Premium
2         Good
5    Very Good
8         Fair
Name: cut, dtype: object

7
0     E
3     I
4     J
7     H
12    F
25    G
28    D
Name: color, dtype: object

8
0       SI2
1       SI1
2       VS1
3       VS2
5      VVS2
6      VVS1
15       I1
229      IF
Name: clarity, dtype: object

In [80]:
cut_quality = {'Fair': 1,
               'Good': 2,
               'Very Good': 3,
               'Premium': 4,
               'Ideal': 5
               }

color_quality = {'J': 1,
                 'I': 2,
                 'H': 3,
                 'G': 4,
                 'F': 5,
                 'E': 6,
                 'D': 7
                 }

clarity_quality = {'I1': 1,
                   'SI2': 2,
                   'SI1': 3,
                   'VS2': 4,
                   'VS1': 5,
                   'VVS2': 6,
                   'VVS1': 7,
                   'IF' : 8
                   }

In [88]:
diam_new['cut_encoded'] = diam_new['cut'].map(cut_quality)
diam_new['color_encoded'] = diam_new['color'].map(color_quality)
diam_new['clarity_encoded'] = diam_new['clarity'].map(clarity_quality)

# diam_new.head()

diam_corr_matrix = diam_new.drop(columns=['cut', 'color', 'clarity'])

diam_corr_matrix.dtypes

weight             float64
depth              float64
table              float64
price                int64
lengh              float64
widht              float64
depth              float64
cut_encoded          int64
color_encoded        int64
clarity_encoded      int64
dtype: object

In [90]:
matrix = diam_corr_matrix.corr()
matrix

,weight,depth,table,price,lengh,widht,depth,cut_encoded,color_encoded,clarity_encoded
weight,1.000000,0.028224,0.181618,0.921591,0.975094,0.951722,0.953387,-0.134967,-0.291437,-0.352841
depth,0.028224,1.000000,-0.295779,-0.010647,-0.025289,-0.029341,0.094924,-0.218055,-0.047279,-0.067384
table,0.181618,-0.295779,1.000000,0.127134,0.195344,0.183760,0.150929,-0.433405,-0.026465,-0.160327
price,0.921591,-0.010647,0.127134,1.000000,0.884435,0.865421,0.861249,-0.053491,-0.172511,-0.146800
lengh,0.975094,-0.025289,0.195344,0.884435,1.000000,0.974701,0.970772,-0.125565,-0.270287,-0.371999
widht,0.951722,-0.029341,0.183760,0.865421,0.974701,1.000000,0.952006,-0.121462,-0.263584,-0.358420
depth,0.953387,0.094924,0.150929,0.861249,0.970772,0.952006,1.000000,-0.149323,-0.268227,-0.366952
cut_encoded,-0.134967,-0.218055,-0.433405,-0.053491,-0.125565,-0.121462,-0.149323,1.000000,0.020519,0.189175
color_encoded,-0.291437,-0.047279,-0.026465,-0.172511,-0.270287,-0.263584,-0.268227,0.020519,1.000000,-0.025631
clarity_encoded,-0.352841,-0.067384,-0.160327,-0.146800,-0.371999,-0.358420,-0.366952,0.189175,-0.025631,1.000000